-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 20:48:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twp` DEFAULT CHARACTER SET utf8 ;
USE `twp` ;

-- -----------------------------------------------------
-- Table `twp`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twp`.`employee` (
  `id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `status` ENUM('0', '1', '2') NOT NULL,
  `role` ENUM('0', '1', '2') NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twp`.`employee_mobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twp`.`employee_mobile` (
  `employee_id` INT UNSIGNED NULL,
  `number` VARCHAR(45) NOT NULL,
  INDEX `id_idx` (`employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twp`.`employee_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twp`.`employee_address` (
  `employee_id` INT UNSIGNED NULL,
  `address` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  INDEX `id_idx` (`employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twp`.`stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twp`.`stage` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twp`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twp`.`task` (
  `id` INT UNSIGNED NOT NULL,
  `message` VARCHAR(128) NOT NULL,
  `stage_id` INT(45) UNSIGNED NULL,
  `employee_id` INT(45) UNSIGNED NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`employee_id` ASC) VISIBLE,
  INDEX `id_idx1` (`stage_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twp`.`employee_avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twp`.`employee_avatar` (
  `employee_id` INT UNSIGNED NULL,
  `avatar` BLOB NULL,
  INDEX `id_idx` (`employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
